apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: $KAFKA_NAMESPACE
spec:
  selector:
    app: kafka-server
  type: NodePort
  ports:
    - port: 9092
      targetPort: kafka-port
      protocol: TCP
