apiVersion: v1
# Kind for service
kind: Service
metadata:
  # Name your service
  name: postgresdb
  namespace: $DATABASE_NAMESPACE
  labels:
    app: postgresdb
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '9187'
spec:
  # Choose how to expose your service
  type: NodePort
  ports:
    # The port number to expose the service
    - name: db-port
      port: 5432
      targetPort: database-port
    - name: db-mon-port
      port: 9187
      targetPort: db-prom-port
  # Pod to route service traffic  
  selector:
    app: postgresdb
