# Kubernetes API version
apiVersion: apps/v1
# Deployment object
kind: Deployment
metadata:
  # The name of the Deployment
  name: postgresdb
  namespace: $DATABASE_NAMESPACE
spec:
  # Replicas for this Deployment
  replicas: 1
  selector:
    # labels the pods
    matchLabels:
      app: postgresdb
  template:
    metadata:
      labels:
        # The label the pods created from the pod template should have
        app: postgresdb
    spec:
      containers:
        # The container name to execute pods
        - name: postgresdb
          # pull postgresimage from docker hub
          image: postgres
          ports:
            # Assign ports to expose container
            - containerPort: 5432
              name: database-port
          envFrom:
            # Load the environment variables/PostgresSQL credentials
            - configMapRef:
                # This should be the ConfigMap name created ealier
                name: db-secret-credentials
          volumeMounts:
            # The volume mounts  for the container
            - mountPath: /var/lib/postgresql_tmp/data
              name: db-data
        - name: postgresdb-monitoring
          # pull postgresimage from docker hub
          image: prometheuscommunity/postgres-exporter
          ports:
            # Assign ports to expose container
            - containerPort: 9187
              name: db-prom-port
          env:
            - name: DATA_SOURCE_NAME
              value: "postgresql://testUser:testPassword@postgresdb:5432/testDB?sslmode=disable"
          envFrom:
            # Load the environment variables/PostgresSQL credentials
            - configMapRef:
                # This should be the ConfigMap name created ealier
                name: db-secret-credentials
      # Volumes attached to the pod
      volumes:
        - name: db-data
          persistentVolumeClaim:
            # reference the PersistentVolumeClaim
            claimName: postgresdb-persistent-volume-claim

