apiVersion: v1
# Kind for volume chain
kind: PersistentVolume
metadata:
  # Name the persistent chain
  name: prometheus-storage
  # Labels for identifying PV
  labels:
    type: local
    app: prometheus
spec:
  storageClassName: manual
  capacity:
    # PV Storage capacity
    storage: 1Gi
  # Prometheus can write and read from volumes to multiple pods
  accessModes:
    - ReadWriteMany
  # Specify the path to persistent the volumes  
  hostPath:
    path: "/data/prometheus"
---
apiVersion: v1
# define a resource for volume chain
kind: PersistentVolumeClaim
metadata:
  # Name the volume chain
  name: prometheus-storage
  namespace: $MONITORING_NAMESPACE
spec:
  storageClassName: manual
  accessModes:
    # Allow ReadWrite to multiple pods
    - ReadWriteMany
  # PVC requesting resources
  resources:
    requests:
      # the PVC storage
      storage: 1Gi

