spring:
  application:
    name: aws-demo
  cloud:
    aws:
      s3:
        endpoint: https://localhost.localstack.cloud:4566
        region: eu-central-1
        #path-style-access-enabled: true
      sqs:
        endpoint: https://localhost.localstack.cloud:4566
        region: eu-central-1
      dynamodb:
        endpoint: https://localhost.localstack.cloud:4566
        region: eu-central-1
      credentials:
        access-key: none
        secret-key: none
      region:
        static: eu-central-1
