spring:
  application:
    name: aws-demo
  cloud:
    aws:
      s3:
        endpoint: https://localhost.localstack.cloud:4566
        region: us-east-1
        #path-style-access-enabled: true
      credentials:
        access-key: none
        secret-key: none
      region:
        static: us-east-1
