spring:
  application:
    name: demokafkasecond
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    streams:
      application-id: my-app
    customers-topic-name: customers-test-topic
    customers-table-topic-name: customers-table-test-topic
