apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: $GMONITORING_NAMESPACE
spec:
  selector:
    app: grafana-server
  type: NodePort
  ports:
    - port: 3000
      targetPort: grafana-port

