apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-app-ingress
  namespace: $NGINX_NAMESPACE
spec:
  ingressClassName: nginx
  rules:
    - host: nginx.localkuber
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80
